# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Movie Title')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Rating out of 10')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('casting', models.CharField(max_length=1000, verbose_name='Castings for the Movie')),
            ],
            options={
                'db_table': 'movie',
                'verbose_name_plural': 'Movies',
                'verbose_name': 'Movie',
            },
        ),
    ]
